### ISSUE TITLE
Action don't check if the label is already applied

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/pull-request-labeler-action#17]
1. Create a PR who add a label automatically
2. Re-push modifications on this PR

If the first push already add a label, Action remove it and add it again.

Behavior expected: Check if the Action already exist and remove it only if it is necessary.

![Capture d’écran 2019-07-29 à 16 31 50](https://user-images.githubusercontent.com/1913901/62056847-c1b2e300-b21e-11e9-95ba-5991d89fa570.png)

**Comment by rdelgatte** [comment]
Hello @GerardPaligot 
Can you please tell me when you tried that because I remembered reworking that behavior few weeks ago in https://github.com/Decathlon/pull-request-labeler-action/pull/14 so you may give it a try again. 
It should cancel the job if no label needs to be added: 

![image](https://user-images.githubusercontent.com/11570518/63257652-897d4e00-c27a-11e9-91a6-d366e8055929.png)
Logs:
![image](https://user-images.githubusercontent.com/11570518/63257593-6783cb80-c27a-11e9-9f04-99e8ea600e14.png)

Please come back to me if it still does not work as expected. 
Thank you in advance

**Comment by lusoalex** [comment]
@GerardPaligot do you still have the problem?

**Comment by GerardPaligot** [comment]
@lusoalex Finally take time for this but I got a new error message during my test: https://github.com/Decathlon/pull-request-labeler-action/pull/25

**Comment by mmornati** [comment]
It seems the problem was related to the GitHub APIs access:
```
✖  fatal     HttpError: Resource not accessible by integration 
    at response.text.then.message (/app/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I think it is OK now as the new PRs are working good.

**Comment by rdelgatte** [comment]
Hello @GerardPaligot, did you get your answer? Should I close this issue?

**Comment by GerardPaligot** [comment]
Yes, we can close the issue. I think everything is ok.
